carrito/urls.py
from django.urls import path
from .views import agregarProducto,decrementarProducto,eliminarProducto,limpiarCarrito


app_name = "cart"
urlpatterns = [
    path('agregarproducto/<int:producto_id>/',agregarProducto,name="agregarproducto"),
    path('eliminarproducto/<int:producto_id>/',eliminarProducto,name="eliminarproducto"),
    path('decrementarproducto/<int:producto_id>/',decrementarProducto,name="decrementarproducto"),
    path('limpiarcarro/',limpiarCarrito,name="limpiarcarrito"),
]

pagbase/urls.py
from django.urls import path,include
from .views import paginaprincipal, listarProducto, modificarProducto, agregarProducto, eliminarProducto,administracion,lista,muestraProducto,categoria,carrito,offline,listarCategorias,modificarCategoria,eliminarCategoria,tiendas
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', paginaprincipal,name="loby"),
    path('listar/', listarProducto, name="listar"),
    path('agregar/', agregarProducto, name='agregar'),
    path('modificar/<int:id_producto>', modificarProducto, name='modificar'),
    path('eliminar/<int:id_producto>', eliminarProducto, name='eliminar'),
    path('administracion/',administracion, name='admin'),
    path('lista/<id>',lista, name='lista'),
    path('productos/<int:id_producto>',muestraProducto, name='muestraProducto'),
    path('categoria/',categoria,name='categoria'),
    path('carrito/',carrito,name='carrito'),
    path('offline/',offline,name='offline'),
    path('listacategorias/',listarCategorias,name='listacategorias'),
    path('modificarcategoria/<int:id>',modificarCategoria,name='modificarcategoria'),
    path('eliminarcategoria/<int:id>',eliminarCategoria,name='eliminarcategoria'),
    path('tiendas/',tiendas,name='tiendas')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
    )

paginaWed/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "cart"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pagbase.urls')),
    path('accounts/', include('usuarios.urls')),
    path('carrito/', include('carrito.urls')),
    path('social/',include('social_django.urls', namespace='social')),
    path('',include('pwa.urls')),
]

carrito/models.py
from django.db import models

# Create your models here.

pagbase/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    Nombre = models.CharField(max_length = 30, null = False, blank = False,)
    def __str__(self):
        return self.Nombre
class Producto(models.Model):
    foto = models.FileField(upload_to='fotos')
    nombre = models.CharField(max_length=50,null=False,blank=False)
    marca = models.CharField(max_length=50,null=False,blank=False)
    modelo = models.CharField(max_length=50,null=False,blank=False)
    precio = models.PositiveIntegerField()
    peso = models.PositiveIntegerField()
    dimension = models.PositiveIntegerField()
    detalle = models.TextField(max_length=300)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

pagbase/forms.py
from django import forms
from .models import Producto,Categoria

def agregarClaseFormControl(elementos):
    for campo in elementos:
        campo.field.widget.attrs['class'] = 'form-control'

class ProductoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductoForm,self).__init__(*args, **kwargs)
        agregarClaseFormControl(self.visible_fields())
        
    class Meta:
        model = Producto
        fields = ['foto','nombre','marca','modelo','precio','peso','dimension','detalle','categoria']

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['Nombre']

carrito/views.py
from django.shortcuts import render, redirect
from pagbase.models import Producto
from django.contrib.auth.decorators import login_required
from .cart import Cart

# Create your views here.
@login_required(redirect_field_name='login')
def agregarProducto(request, producto_id):
    cart = Cart(request)
    producto = Producto.objects.get(id = producto_id)
    cart.add(producto = producto)
    return redirect('/carrito/')
@login_required(login_url="/accounts/login/")
def eliminarProducto(request, producto_id):
    cart = Cart(request)
    producto = Producto.objects.get(id = producto_id)
    cart.remove(producto)
    context = {
        'producto':producto,
    }
    return redirect("/carrito/")
@login_required(login_url="/accounts/login/")
def decrementarProducto(request, producto_id):
    cart = Cart(request)
    producto = Producto.objects.get(id = producto_id)
    cart.decrement(producto = producto)
    return redirect("/carrito/")
@login_required(login_url="/accounts/login/")
def limpiarCarrito(request):
    cart = Cart(request)
    cart.clear()
    return redirect("/carrito/")

pagbase/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
# Create your views here.
from .models import Producto, Categoria
from .forms import ProductoForm, CategoriaForm
from usuarios.forms import inicioForm
from carrito.cart import Cart
from django.core.paginator import Paginator
from django.contrib.auth.decorators import permission_required

def paginaprincipal(request):
    cart = Cart(request)
    formulario = AuthenticationForm()
    usuario = AuthenticationForm()
    lista = Categoria.objects.all()
    if request.method == 'POST':
        formulario = AuthenticationForm(data=request.POST)
        if formulario.is_valid():
            username = formulario.cleaned_data['username']
            password = formulario.cleaned_data['password']
            usuarioLogeado = authenticate(username=username, password=password)
            if usuarioLogeado is not None:
                login(request, usuarioLogeado)
                if usuarioLogeado.username == 'admin':
                    return redirect('/administracion/')
                else:
                    return redirect('/')
    context = {
        'titulo': 'Tiendita del Cris',
        'formulario2': formulario,
        'lista': lista
    }
    return render(
        request,
        'pagbase/principal.html',
        context
    )

@permission_required('view_group')
def agregarProducto(request):
    lista = Categoria.objects.all()
    formulario = None
    if request.method == 'POST':
        formulario = ProductoForm(request.POST, request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect('/listar/')
    else:
        formulario = ProductoForm()
    context = {
        'titulo': 'Agregar Producto',
        'formulario': formulario,
        'lista': lista,
    }
    return render(
        request,
        'pagbase/agregar.html',
        context
    )
@permission_required('change_producto')
def modificarProducto(request, id_producto):
    productoRecibido = Producto.objects.get(pk=id_producto)
    lista = Categoria.objects.all()
    formulario = None
    if request.method == 'POST':
        formulario = ProductoForm(request.POST, instance=productoRecibido)
        if formulario.is_valid():
            formulario.save()
            return redirect('/listar/')
    else:
        formulario = ProductoForm(instance=productoRecibido)
    context = {
        'titulo': 'Modificar Producto',
        'formulario': formulario,
        'lista': lista,
    }
    return render(
        request,
        'pagbase/modificar_t.html',
        context
    )

@permission_required('view_producto')
def listarProducto(request):
    productos = Producto.objects.all()
    lista = Categoria.objects.all()
    context = {
        'titulo': 'Productos',
        'productos': productos,
        'lista': lista,
    }
    return render(
        request,
        'pagbase/listarTecnologia.html',
        context
    )

@permission_required('delete_producto')
def eliminarProducto(request, id_producto):
    productoEliminado = Producto.objects.get(pk=id_producto)
    productoEliminado.delete()
    return (redirect('/listar/'))

@permission_required('view_producto')
def administracion(request):
    lista = Categoria.objects.all()
    context = {
        'titulo': 'Administrador',
        'lista': lista,
    }
    return render(
        request,
        'admin/admin.html',
        context
    )


def lista(request, id):
    cart = Cart(request)
    productos = Producto.objects.filter(categoria_id__exact=id)
    formulario2 = AuthenticationForm()
    lista = Categoria.objects.all()
    if request.method == 'POST':
        formulario2 = AuthenticationForm(data=request.POST)
        if formulario2.is_valid():
            username = formulario2.cleaned_data['username']
            password = formulario2.cleaned_data['password']
            usuarioLogeado = authenticate(username=username, password=password)
            if usuarioLogeado is not None:
                login(request, usuarioLogeado)
                return redirect('/')
        
    paginator = Paginator(productos, 6)
    page = request.GET.get('page')
    productos = paginator.get_page(page)

    context = {
        'titulo': 'lista',
        'productos': productos,
        'formulario2': formulario2,
        'lista':lista
    }
    return render(
        request,
        'pagbase/catalogoModa.html',
        context
    )



def muestraProducto(request, id_producto):
    lista = Categoria.objects.all()
    productoRecibido = Producto.objects.get(pk=id_producto)
    formulario2 = AuthenticationForm()
    if request.method == 'POST':
        formulario2 = AuthenticationForm(data=request.POST)
        if formulario2.is_valid():
            username = formulario2.cleaned_data['username']
            password = formulario2.cleaned_data['password']
            usuarioLogeado = authenticate(username=username, password=password)
            if usuarioLogeado is not None:
                login(request, usuarioLogeado)
                return redirect('/')
    context = {
        'titulo': 'Productos',
        'producto': productoRecibido,
        'lista': lista,
        'formulario2': formulario2,
    }
    return render(
        request,
        'pagbase/datosProductos.html',
        context
    )

@permission_required('view_producto')
def categoria(request):
    usuario = AuthenticationForm()
    lista = Categoria.objects.all()
    formulario = None
    if request.method == 'POST':
        formulario = CategoriaForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('/')
    else:
        formulario = CategoriaForm()
    context = {
        'titulo': 'Agregar Categoria',
        'formularioC': formulario,
        'lista': lista,
        'usuario': usuario,

    }
    return render(
        request,
        'admin/categoria.html',
        context
    )
def carrito(request):
    lista = Categoria.objects.all()
    usuario = AuthenticationForm()
    context = {
        'titulo': 'Carrito',
        'lista': lista,
        'usuario': usuario,
    }    
    return render(
        request,
        'pagbase/carrito.html',
        context
    )

def offline(request):
    lista = Categoria.objects.all()
    usuario = AuthenticationForm()
    context = {
        'titulo': 'offline',
        'lista': lista,
        'usuario': usuario,
    }    
    return render(
        request,
        'offline.html',
        context
    )

def listarCategorias(request):
    categorias = Categoria.objects.all()
    lista = Categoria.objects.all()
    context = {
        'titulo':'Categorías',
        'categorias': categorias,
        'lista': lista
    }
    return render(
        request,
        'pagbase/listarCategorias.html',
        context
    )

def modificarCategoria(request, id):
    categoria = Categoria.objects.get(pk = id)
    lista = Categoria.objects.all()
    formulario = None
    if request.method == 'POST':
        formulario = CategoriaForm(request.POST, instance = categoria)
        if formulario.is_valid():
            formulario.save()
            return redirect('/listacategorias/')
    else:
        formulario = CategoriaForm(instance = categoria)
    context = {
        'titulo': 'Modificar categoría',
        'formulario': formulario,
        'lista': lista
    }
    return render(
        request,
        'pagbase/modificarCategoria.html',
        context
    )

def eliminarCategoria(request, id):
    categoria = Categoria.objects.get(pk = id)
    categoria.delete()
    return redirect('/listacategorias/')

def tiendas(request):
    context = {
        'titulo': 'tiendas',
    }    
    return render(
        request,
        'pagbase/tienda.html',
        context
    )

templates/pagbase/Tecnologia.html
{% extends 'pagbase/ingreso.html' %}
{% block contenido2 %}
{%if productos%}
<section class="row">
    <table>
        <thead>
            <tr>
                <th>imagen</th>
                <th>nombre</th>
                <th>marca</th>
                <th>modelo</th>
                <th>dimensiones</th>
                <th>peso</th>
                <th>detalle</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
                <td id="{{producto.id}}"></td>
                <td>{{producto.link}}</td>
                <td>{{producto.nombre}}</td>
                <td>{{producto.marca}}</td>
                <td>{{producto.modelo}}</td>
                <td>{{producto.dimensiones}}</td>
                <td>{{producto.peso}}</td>
                <td>{{producto.detalle}}</td>
            </tr>
            {% endfor%}
        </tbody>
    </table>
</section>
{% else %}
<p>no se encuentran productos disponibles</p>
{% endif %}
{% endblock %}

templates/pagbase/agregar.html
<div class="row">
    <section class="card col-sm-12 col-md-6 mx-auto mt-5">
        <article class="card-header" style="display: flex; justify-content: center;">
            <img class="imagen-producto"  src="https://image.flaticon.com/icons/png/512/2225/2225147.png" style="max-height: 50px; max-width:50px;">   
        </article>
        <form action="" method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            <article class="card-body">
                {{ formulario.as_p }}
            </article>
            <article class="card-footer" style="display: flex; justify-content: center;">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="width: 50%">Guardar
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-90deg-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M14.854 4.854a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 4H3.5A2.5 2.5 0 0 0 1 6.5v8a.5.5 0 0 0 1 0v-8A1.5 1.5 0 0 1 3.5 5h9.793l-3.147 3.146a.5.5 0 0 0 .708.708l4-4z"/>
                  </svg>
            </button>
            </article>
        </form>
    </section>
</div>

templates/pagbase/bannerSuperior.html
{% extends 'base/index.html' %}
{% block header %}
<header>
    <picture>
        <img id="logoWeb" src="https://i.pinimg.com/564x/00/40/8e/00408e0124295dc94dbab93d7c64ccb2.jpg"> 
    </picture>
    <section  id="barra-superior">
        <article class="flex">
            <p id="superior" class="espacio">Venta Telefonica</p>
            <p id="superior">Contacto</p>
            <p id="centro">La Tiendita</p>
            <a id="derecha" href="" ><img src="https://www.falabella.com/a/fa/static/styles/svg/flagCl.svg"> </a>
 
        </article>
    </section>
    <section id="barra-inferior">
        <article class="flex">
            <article class="flex" id="menu">
                <p class='dropdown-trigger btn' href='#' data-target='dropdown' id="margen"> <i class="material-icons" >menu</i></p>
                <ul id='dropdown' class='dropdown-content'>
                    <li><a type="submit" href="/principal/listar" class="tecnologia">Tecnologia</a></li>
                    <li><a type="submit" href="#!" class="moda">Moda</a></li>
                    <li><a type="submit" href="#!" class="volver">Pagina principal</a></li>
                    <li><a type="submit" href= "/principal/agregar"class="agregar">agregar</a></li>
                    <li><a type="submit" href="#!" class="eliminar">Eliminar</a></li>
                </ul>
            </article>
            <section class="flex" id="buscar">
                <input type="search" placeholder="¿Qué buscas?">
            </section>
                <a href="#" id="cuenta"><i class="material-icons">perm_identity</i><br>Cuenta</a>
                <a href="#" id="cuenta" class="compras">Mis Compras</a>
                <a href="#" id="cuenta" class="ayuda">Ayuda</a>
                <a href="#" id="cuenta">Bolsas</a>
            </article>
        </article>
    </section>

</header>
{% endblock header%}

templates/pagbase/carrito.html
{% extends 'base/index.html' %}
{% block main %}
    {% include "carrito/widget.html" %}
{% endblock main %}

templates/pagbase/catalogoModa.html
{% extends 'base/index.html' %}

{% load cart_tags %}


{% block main %}
</form>

</body>
<main class="container col-sm-12 col-md-6 mx-auto mt-5" style="display: flex; margin: 0 !important; min-width: 100%; padding-top: 50px;">
  <section id = "catalogoProductos" class="card-group col-sm-12 col-md-6 mx-auto mt-5" style="display: flex; min-width: 100%; margin: 0 !important; justify-content: center;">
    {% for producto in productos %}
    <div class="card " style="max-width: 250px; margin: 10px" id="{{producto.id}}">
      <img src="/media/{{producto.foto}}" style=" width: 300px; height: 200px;" class="img-thumbnail" alt="{{producto.nombre}}">
      <div class="card-body">

          <h5 class="card-title"> {{producto.nombre}}</h5>
          <p class="">Precio: ${{producto.precio}}</p>

      </div>
      
      <footer class="card-footer" id = "card-footer-moda">
        <div class="btn-group" role="group" aria-label="Basic example"></div>
        <a href="/productos/{{producto.id}}" class="card-link btn btn-primary" style="margin: 5px;">Visualizar</a><br>
        <a href="{% url 'cart:agregarproducto' producto_id=producto.id %}" class="card-link btn btn-primary">Agregar al carrito</a>
        </div>
    </footer>
    </div>
    {% endfor %}
  </section>
</main>
  <div class="row" style="display: flex; margin: 10px;">
    <div class="col-md-16 col-lg-12 col-sm-12 col-xs-12">
      <div class="col-md-6 float-left">
        {% if productos.has_previous %}
          <div class="clearfix">
            <a href="?page={{productos.previous_page_number}}" class="btn btn-primary float-left">Anterior</a>
        {% endif %}
      </div>
    </div>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
      <div class="col-md-12 float-left">
        {% if productos.has_next %}
          <div class="clearfix">
            <a href="?page={{productos.next_page_number}}" class="btn btn-primary float-right">Siguiente</a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/pagbase/cuerpo.html
{% extends 'pagbase/ingreso.html' %}
{% block contenido2 %}
   <!--Agregar-->
   <main id ="pagina-agregar">
      <section class="datos-producto">
          <img class="imagen-producto" src="https://scontent-scl2-1.cdninstagram.com/v/t51.2885-15/e35/65110435_471970740301919_1632220654426317265_n.jpg?_nc_ht=scontent-scl2-1.cdninstagram.com&_nc_cat=111&_nc_ohc=ELX6oeXG8jkAX8yUTpS&_nc_tp=18&oh=6077b8440fe942bfc1bd762e09159b9f&oe=5F92B5EC"/>
          <form onsubmit="" class="formulario" id="formulario">
              <div>
                  <h2>Ingrese link de la imagen</h2>
                  <input class="input-text" type="text" name="imagen" required>
              </div>
               <div>
                  <h2>Categoria</h2>
                  <select name="categorias" id="categorias">
                      <!--<option value="0">Seleccionar</option>--> 
                      <option value="0">Seleccionar</option>
                      <option value="tecnologia"> Tecnologia</option>
                      <option value="moda"> moda</option>
                  </select>
              </div>
              <div>
                  <h2>Marca</h2>
                  <input class="input-text" type="text" name="marca" minlength="2" maxlength="30" required> 
              </div>
              <div>
                  <h2>Modelo</h2>
                  <input class="input-text" type="text" name="modelo" minlength="2" required>
              </div>
              <div>
                  <h2>Dimensiones</h2>
                  <input class="input-text" type="text" name="dimensiones" minlength="3" required>
              </div>
              <div>
                  <h2>Peso (en kg)</h2>
                  <input class="input-text" type="number" name="peso" minlength="1" step="0.01" min="0" required>
              </div>
              <div>
                  <h2>Precio</h2>
                  <input class="input-text" step="10" type="number" name="precio" minlength="3" maxlength="9" min="990" max="9999999" required>
              </div>
              <div>
                  <h2>Características del producto</h2>
                  <input class="input-desc" type="text" name="caracteristicas" minlength="10" required/>
              </div>
              <div>
                  <input  type="submit" value="Agregar" >
              </div>
          </form>
      </section>
      <section id="lista">
          
      </section>
  </main>
{% endblock %}

templates/pagbase/datosProductos.html
{% extends 'base/index.html' %}
{% load static %}
{% block main %}
<main class="container" style="padding-top: 50px;">
    <article class="row row-cols-1 row-cols-sm-2 row-cols-md-12 detprod ">
        <section class="text-center align-self-center border-right " >
            <img src="/media/{{producto.foto}}" class="m-2 sm-12 border-secondary border border-primary" alt=""
                style="width: 300px; height: 300px;">
        </section>
            <nav class="row" style="align-content: space-evenly; background-color: #fafafa;">
                <h3 class="col-12 text-center"> Información del producto </h3>
                <p class="col-6" style="padding-left: 30px;">Nombre: {{producto.nombre}}</p>
                <p class="col-6">Marca: {{producto.marca}}</p>
                <p class="col-6" style="padding-left: 30px;">Precio: ${{producto.precio}}</p>
                <p class="col-6">Peso: {{producto.peso}}Kg</p>
                <p class="col-6" style="padding-left: 30px;">Dimension: {{producto.dimension}}</p>
                <p class="col-6">Detalle: {{producto.detalle}}</p>
                <p class="text-center col-12">
                    <a href="{% url 'cart:agregarproducto' producto_id=producto.id %}" class="btn btn-primary col-8 ">Agregar al
                        Carrito</a>
                </p>
                
            </nav>
    </article>
</main>

<div class="card" style="width: 100%; margin: 1%;">
    <div class="card-header">
        <h2 class="card-tittle">Comentarios</h2>
    </div>
    <form action="">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="comentario">Ingrese su comentario...</label>
                        <textarea name="comentario" id="comentario" required class = "form-control" cols="30" rows="10"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Comentar" class = "btn btn-success btn-block">
        </div>
    </form>
</div>
<section class="container">

</section>


{% endblock %}

templates/pagbase/ingreso.html
{% extends 'base/contenido.html' %}
{% block contenido %}
<header>
    <picture herf="/principal/">
        <img id="logoWeb"  src="https://i.pinimg.com/564x/00/40/8e/00408e0124295dc94dbab93d7c64ccb2.jpg"> 
    </picture>
    <section  id="barra-superior">
        <article class="flex">
            <p id="superior" class="espacio">Venta Telefonica</p>
            <p id="superior">Contacto</p>
            <p id="centro">La Tiendita</p>
            <a id="derecha" href="#!" ><img src="https://www.falabella.com/a/fa/static/styles/svg/flagCl.svg"> </a>
 
        </article>
    </section>
    <section id="barra-inferior">
        <article class="flex">
            <article class="flex" id="menu">
                <p class='dropdown-trigger btn' href='#' data-target='dropdown' id="margen"> <i class="material-icons" >menu</i></p>
                <ul id='dropdown' class='dropdown-content'>
                    <li><a type="submit" href="#!" class="tecnologia">Tecnologia</a></li>
                    <li><a type="submit" href="#!" class="moda">Moda</a></li>
                    <li><a type="submit" href="#!" class="volver">Pagina principal</a></li>
                    <li><a type="submit" href="/principal/cuerpo" class="agregar">agregar</a></li>
                    <li><a type="submit" href="#!" class="eliminar">Eliminar</a></li>
                </ul>
            </article>
            <section class="flex" id="buscar">
                <input type="search" placeholder="¿Qué buscas?">
            </section>
                <a href="#" id="cuenta"><i class="material-icons">perm_identity</i><br>Cuenta</a>
                <a href="#" id="cuenta" class="compras">Mis Compras</a>
                <a href="#" id="cuenta" class="ayuda">Ayuda</a>
                <a href="#" id="cuenta">Bolsas</a>
            </article>
        </article>
    </section>

</header>
{% endblock %}
{% block contenido2 %}
<main id = "pagina-principal" class="principal">
    <!-- slider de  imagenes-->
    <picture>
        <!--Lista de imagenes-->
        <div class="slider">
            <ul class="slides">
                <li>
                    <img src="https://neoattack.com/blog/wp-content/uploads/2021/11/PORTADA-ESTRATEGIAS-DE-PROMOCION-VENTAS.jpg" width: 580;>
                </li>
                <li>
                    <img src="https://mipropiojefe.com/wp-content/uploads/2019/03/promociones-efectivas.jpg">
                </li>
                <li>
                    <img src="https://mipropiojefe.com/wp-content/uploads/2022/09/blgmp-22sp2.jpg">
                </li>
                <li>
                    <img src="https://mipropiojefe.com/wp-content/uploads/2022/09/nuevo_competidor.jpg">
                </li>
            </ul>
        </div>
    </picture>
    <!--Seccion informaciónes-->
    <section>

    </section>
    <!--Seccion de productos-->
    <section id = "productos" class ="row display-flex">
        <article class = "col s2 display-flex"><a class = "display-flex" href = "#">Conoce más aquí</a></article>
        <article class = "col s2 display-flex"><a class = "display-flex" href = "#">Conoce más aquí</a></article>
        <article class = "col s2 display-flex"><a class = "display-flex" href = "#">Conoce más aquí</a></article>
        <article class = "col s2 display-flex"><a class = "display-flex" href = "#">Conoce más aquí</a></article>
    </section>
    <!--Promocion plan-->
    <aside id = "promocion-1" class="display-flex">
        <article class = "col s12">
            
        </article>
    </aside>
    <!--promocion acumula puntos-->
    <aside id = "promocion-2" class = "row display-flex">
        <article class = "col s12">
            <a href = "#"></a>
        </article>

    </aside>
    <!--Seccion de imperdibles con display grid-->
    <!--Usar background image-->
    <!--El uso de img limita el despliegue de la imagen a la altura y ancho que posee-->
    <section id="imperdibles" class="row">
        <article class="col s6"></article>
        <article class="col s3"></article>
        <article class="col s3"></article>
        <article class="col s3"></article>
        <article class="col s3"></article>
        <article class="col s6"></article>
        <article class="col s6"></article>
        <article class="col s3"></article>
        <article class="col s3"></article>
        <article class="col s3"></article>
        <article class="col s3"></article>
        <article class="col s6"></article>
    </section>
    <!--seccion imperdibles (se despliega en la version movil)-->
    <section id = "imperdibles-mobile">
        <article></article>
        <article></article>
        <article></article>
        <article></article>
        <article></article>
        <article></article>
        <article></article>
        <article></article>
        <article></article>
        <article></article>
        <article></article>
        <article></article>
    </section>

    <!--slider de recomendaciones de clientes-->
    <section id = "lo-encontre" class = "display-flex row">
        <article class = "col s6"></article>
        <article class = "col s3"></article>
        <article class = "col s3"></article>
    </section>
    </main>
{% endblock contenido2 %}

templates/pagbase/tienda.html
{% extends 'base/index.html' %}
{% block main %}
<h1 class="mx-auto">NUESTRAS TIENDAS</h1>
<div id="map"></div>
{% endblock main %}
{% block js %}

{% endblock js %}